"""
Daily PFAS intake calculation for dairy goats.

New, Excel-consistent pipeline:

- Reads hay PFAS concentrations from:
    data/original/PFAS-Gehalte.xlsx  (sheet: Heu_neu_Pool)
- Reads per-animal feed intake and milk yield from:
    data/raw/animal_data.csv         (generated by data/scripts/generate_animal_data_csv.py)

For each day, animal, and compound–isomer, we compute:

    Intake_ug_day = Hay_Concentration_ug_kg(day, compound, isomer) × Feed_Intake_kg_day(animal, day)

Hay concentrations are applied as a step function over time based on the
sampling days in Heu_neu_Pool (column Tag).

Primary output (used as model input):
  - data/processed/pfas_daily_intake.csv
"""

from pathlib import Path
from typing import Tuple
import sys

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Run from project root: python mass_balance/intake.py  or  python -m mass_balance.intake
_CLEAN_ROOT = Path(__file__).resolve().parent.parent
if str(_CLEAN_ROOT) not in sys.path:
    sys.path.insert(0, str(_CLEAN_ROOT))

from auxiliary.project_paths import get_data_root, get_results_root
from auxiliary.plot_style import set_paper_plot_style

# Apply global figure/plot style (shared with other plots)
set_paper_plot_style()


# Exposure period (days) – intake is non-zero only during this period
EXPOSURE_PERIOD_DAYS: int = 56

# Maximum day to generate (end of the experiment)
MAX_DAY: int = 140

# Animal IDs (Tierdaten animals)
ANIMALS = ["E2", "E3", "E4"]


def _get_paths() -> dict:
    """
    Resolve input and output paths within the clean data directory.
    """
    data_root = get_data_root()

    pfas_data_file = data_root / "original" / "PFAS-Gehalte.xlsx"
    animal_data_file = data_root / "raw" / "animal_data.csv"
    output_file = data_root / "processed" / "pfas_daily_intake.csv"

    return {
        "pfas_data_file": pfas_data_file,
        "animal_data_file": animal_data_file,
        "output_file": output_file,
    }


def load_data(file_path_hay: Path, file_path_animal: Path) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load hay PFAS concentrations and per-animal intake data.
    """
    if not file_path_hay.exists():
        raise FileNotFoundError(f"Data file not found: {file_path_hay}")

    if not file_path_animal.exists():
        raise FileNotFoundError(f"Data file not found: {file_path_animal}")

    # Hay PFAS concentrations from Heu_neu_Pool sheet
    xls = pd.ExcelFile(file_path_hay)
    hay_df = pd.read_excel(xls, sheet_name="Heu_neu_Pool")

    # Per-animal intake and milk yield
    animal_df = pd.read_csv(file_path_animal)

    return hay_df, animal_df


def _extract_hay_concentrations(hay_df: pd.DataFrame) -> dict:
    """
    Build a dict mapping (compound, isomer, day) -> hay concentration (µg/kg)
    using the Heu_neu_Pool sheet.

    We treat 'Tag' as sampling day and apply concentrations as a step
    function: for model day d, use the last Tag <= d.
    """
    conc_by_pair_day: dict[tuple[str, str, int], float] = {}

    # Identify PFAS columns with n-/br- prefixes
    pfas_cols = []
    for col in hay_df.columns:
        name = str(col).strip()
        if name.startswith("n-") or name.startswith("br-"):
            prefix, rest = name.split("-", 1)
            compound = rest.strip()
            isomer = "Linear" if prefix == "n" or prefix == "n" else "Linear"
            if name.startswith("br-"):
                isomer = "Branched"
            pfas_cols.append(((compound, isomer), col))

    # Tag column (day of sampling)
    tag_col = "Tag"
    if tag_col not in hay_df.columns:
        raise ValueError("Expected 'Tag' column in Heu_neu_Pool sheet")

    tags = hay_df[tag_col].dropna().astype(int).unique()
    tags = sorted(tags)

    # For each PFAS column, compute step-function concentrations by day
    for (compound, isomer), col in pfas_cols:
        sub = hay_df[[tag_col, col]].dropna(subset=[tag_col, col])
        if sub.empty:
            continue
        sub[tag_col] = sub[tag_col].astype(int)
        # Unique tag -> value (take first per tag)
        tag_vals = (
            sub.drop_duplicates(subset=[tag_col])
            .set_index(tag_col)[col]
            .astype(float)
        )
        available_tags = sorted(tag_vals.index.unique())
        for day in range(1, MAX_DAY + 1):
            prev = [t for t in available_tags if t <= day]
            if prev:
                t = prev[-1]
                c = float(tag_vals.loc[t])
            else:
                c = 0.0
            conc_by_pair_day[(compound, isomer, day)] = c

    return conc_by_pair_day


def combined_intake_dataframe(animal_df: pd.DataFrame, hay_df: pd.DataFrame) -> pd.DataFrame:
    """
    Build the full daily PFAS intake table from hay and per-animal intake data.
    """
    # Build hay concentration lookup
    conc_by_pair_day = _extract_hay_concentrations(hay_df)

    # Restrict animal data to relevant animals and days (Day 0 = baseline same date as Day 1)
    animal_df = animal_df[animal_df["Animal"].isin(ANIMALS)].copy()
    animal_df = animal_df[(animal_df["Day"] >= 0) & (animal_df["Day"] <= MAX_DAY)].copy()

    # Derive list of compound–isomer pairs from hay columns
    pairs = sorted(
        {
            (compound, isomer)
            for (compound, isomer, _day) in conc_by_pair_day.keys()
        }
    )

    # Prefer day-2 feed intake for day 1 when day 1 is zero (first exposure day should have intake)
    day2_feed_by_animal = {}
    for animal in ANIMALS:
        sub = animal_df[(animal_df["Animal"] == animal) & (animal_df["Day"] == 2)]
        day2_feed_by_animal[animal] = float(sub["Feed_Intake_kg_per_day"].iloc[0]) if not sub.empty else 0.0

    results = []
    for day in range(0, MAX_DAY + 1):
        in_exposure = 1 <= day <= EXPOSURE_PERIOD_DAYS
        for animal in ANIMALS:
            sub = animal_df[(animal_df["Animal"] == animal) & (animal_df["Day"] == day)]
            feed_intake = float(sub["Feed_Intake_kg_per_day"].iloc[0]) if not sub.empty else 0.0
            if day == 1 and feed_intake == 0.0 and day2_feed_by_animal.get(animal, 0.0) > 0:
                feed_intake = day2_feed_by_animal[animal]

            for compound, isomer in pairs:
                if in_exposure and feed_intake > 0:
                    hay_conc = conc_by_pair_day.get((compound, isomer, day), 0.0)
                    intake = hay_conc * feed_intake
                else:
                    hay_conc = 0.0
                    intake = 0.0

                results.append(
                    {
                        "Animal": animal,
                        "Day": day,
                        "Compound": compound,
                        "Isomer": isomer,
                        "PFAS_Intake_ug_day": float(intake),
                        "Hay_Concentration_ug_kg": hay_conc if in_exposure else None,
                        "Feed_Intake_kg_day": feed_intake,
                    }
                )

    intake_df = pd.DataFrame(results)
    return intake_df


def main() -> None:
    """
    Entry point: compute and save daily PFAS intake table.
    """
    paths = _get_paths()

    hay_df, animal_df = load_data(paths["pfas_data_file"], paths["animal_data_file"])
    intake_df = combined_intake_dataframe(animal_df, hay_df)

    # Save data
    paths["output_file"].parent.mkdir(parents=True, exist_ok=True)
    intake_df.to_csv(paths["output_file"], index=False)

    print(f"Intake data saved to {paths['output_file']}")


if __name__ == "__main__":
    main()

